version: 0.2

env:
  variables:
    SAM_CLI_TELEMETRY: 0
    ARTIFACT_BUCKET: codebuild-artifacts-bucuket-1668

phases:
  install:
    runtime-versions:
      python: 3.11
    
    commands: 
      - echo "Check if sam exists"
      - sam --version || echo "SAM CLI not found, proceeding to install."
      - echo "Installing AWS SAM CLI..."
      - pip install --upgrade pip
      - pip install aws-sam-cli
      - sam --version

  pre_build:
    commands:
      - echo "=== Checking repository structure ==="
      - pwd
      - ls -la
      - echo "=== Checking lambda directories ==="
      - ls -la lambdas/
      - ls -la lambdas/ec2_analyzer/
      - echo "=== Checking lambda_function.py exists ==="
      - test -f lambdas/ec2_analyzer/lambda_function.py && echo "✓ ec2_analyzer/lambda_function.py exists" || echo "✗ MISSING!"
      - test -f lambdas/rds_analyzer/lambda_function.py && echo "✓ rds_analyzer/lambda_function.py exists" || echo "✗ MISSING!"
      - test -f lambdas/ebs_analyzer/lambda_function.py && echo "✓ ebs_analyzer/lambda_function.py exists" || echo "✗ MISSING!"
      - test -f lambdas/s3_analyzer/lambda_function.py && echo "✓ s3_analyzer/lambda_function.py exists" || echo "✗ MISSING!"
      
      - echo "Run tests if they exist"
      - |
        if [ -d "tests" ]; then
          echo "Running unit tests..."
          pip install pytest boto3 moto pytest-cov
          cd tests && pytest -v --cov=../lambdas
          cd ..
          echo "Tests passed successfully."
          pytest tests/
        else
          echo "No tests directory found, skipping tests."
        fi


  build:
    commands:
      - echo "Checking source lambda directories..."
      - ls -la lambdas/ec2_analyzer/
      - cat lambdas/ec2_analyzer/lambda_function.py | head -20


      - echo "Building SAM application..."
      - sam build --use-container
      - echo "SAM build completed"
      - echo "Build folder structure:"
      - ls -R .aws-sam/build/
      
      - echo "Validating SAM template..."
      - sam validate
      
      - echo "Packaging SAM application..."
      - sam package --s3-bucket $ARTIFACT_BUCKET --output-template-file packaged.yaml
      - echo "SAM package completed"

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - packaged.yaml

